name: sagittarius
description: A simple Dart web server with /hello endpoint.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^5.0.0
  shelf_hotreload: ^1.4.1
